DROP TABLE TEAM CASCADE; 
DROP TABLE PLAYER_BIRTH CASCADE;
DROP TABLE PLAYER CASCADE;
DROP TABLE GAME CASCADE;
DROP TABLE SEASON_TYPE CASCADE;
DROP TABLE SEASON CASCADE;
DROP TABLE PLAYER_GAME_SEASON_LINK CASCADE;
DROP TABLE TEAM_GAME_SEASON_LINK CASCADE;
DROP TABLE INJURY CASCADE;
DROP TABLE PLAYER_INJURY_LINK CASCADE;
DROP TABLE TRADE CASCADE;
DROP TABLE PLAYER_TRADE_LINK CASCADE;
DROP TABLE TEAM_TRADE_LINK CASCADE;
DROP TABLE GUARD CASCADE;
DROP TABLE FORWARD CASCADE;
DROP TABLE CENTER CASCADE;
DROP SEQUENCE player_seq;
DROP SEQUENCE team_seq;
DROP SEQUENCE game_seq;
DROP SEQUENCE player_game_link_seq;
DROP SEQUENCE team_game_link_seq;
DROP SEQUENCE season_seq;
DROP SEQUENCE season_type_seq;
DROP SEQUENCE player_birth_seq;
DROP SEQUENCE injury_seq;
DROP SEQUENCE player_injury_link_seq;
DROP SEQUENCE trade_seq;
DROP SEQUENCE player_trade_link_seq; 
DROP SEQUENCE team_trade_link_seq;

--TABLES
CREATE TABLE TEAM(
TEAM_ID DECIMAL(12) NOT NULL,
TEAM_NAME VARCHAR(32) NOT NULL,
TEAM_HISTORY DECIMAL(3) NOT NULL,
TEAM_LOCATION VARCHAR(64) NOT NULL,
PRIMARY KEY (TEAM_ID));

CREATE TABLE PLAYER_BIRTH(
PLAYER_BIRTH_ID DECIMAL(12) NOT NULL,
BIRTH_DATE DATE NOT NULL,
AGE DECIMAL(3) NOT NULL,
PRIMARY KEY (PLAYER_BIRTH_ID));

CREATE TABLE PLAYER(
PLAYER_ID DECIMAL(12) NOT NULL,
TEAM_ID DECIMAL(12) NOT NULL,
PLAYER_FIRST_NAME VARCHAR(32) NOT NULL,
PLAYER_LAST_NAME VARCHAR(32) NOT NULL,
HEIGHT DECIMAL(3) NOT NULL,
WEIGHT DECIMAL(3) NOT NULL,
COUNTRY VARCHAR(64) NOT NULL,
BIRTH_DATE_ID DECIMAL(12) NOT NULL,
PLAYER_POSITION CHAR(1) NOT NULL,
PRIMARY KEY (PLAYER_ID),
FOREIGN KEY (TEAM_ID) REFERENCES TEAM,
FOREIGN KEY (BIRTH_DATE_ID) REFERENCES PLAYER_BIRTH);

CREATE TABLE GAME(
GAME_ID DECIMAL(12) NOT NULL,
GAME_LOCATION VARCHAR(64) NOT NULL,
GAME_DATE DATE NOT NULL,
PRIMARY KEY (GAME_ID));

CREATE TABLE SEASON_TYPE(
SEASON_TYPE_ID DECIMAL(12) NOT NULL,
SEASON_TYPE VARCHAR(32) NOT NULL,
NUMBER_GAME DECIMAL(3) NOT NULL,
PRIMARY KEY (SEASON_TYPE_ID));

CREATE TABLE SEASON(
SEASON_ID DECIMAL(12) NOT NULL,
SEASON_TYPE_ID DECIMAL(12) NOT NULL,
SEASON_YEAR VARCHAR(32) NOT NULL,
PRIMARY KEY (SEASON_ID),
FOREIGN KEY (SEASON_TYPE_ID) REFERENCES SEASON_TYPE);

CREATE TABLE PLAYER_GAME_SEASON_LINK(
PLAYER_GAME_LINK_ID DECIMAL(12) NOT NULL,
PLAYER_ID DECIMAL(12) NOT NULL,
GAME_ID DECIMAL(12) NOT NULL,
SEASON_ID DECIMAL(12) NOT NULL,
MIN_PLAYED DECIMAL(3, 1),
PTS DECIMAL(3),
REB DECIMAL(3),
AST DECIMAL(3),
STL DECIMAL(3),
BLK DECIMAL(3),
TOV DECIMAL(3),
PRIMARY KEY (PLAYER_GAME_LINK_ID),
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER,
FOREIGN KEY (GAME_ID) REFERENCES GAME,
FOREIGN KEY (SEASON_ID) REFERENCES SEASON);

CREATE TABLE TEAM_GAME_SEASON_LINK(
TEAM_GAME_LINK_ID DECIMAL(12) NOT NULL,
TEAM_ID DECIMAL(12) NOT NULL,
GAME_ID DECIMAL(12) NOT NULL,
SEASON_ID DECIMAL(12) NOT NULL,
TEAM_PTS DECIMAL(3),
TEAM_REB DECIMAL(3),
TEAM_AST DECIMAL(3),
TEAM_STL DECIMAL(3),
TEAM_BLK DECIMAL(3),
TEAM_TOV DECIMAL(3),
WIN_LOSE VARCHAR(32),
PRIMARY KEY (TEAM_GAME_LINK_ID),
FOREIGN KEY (TEAM_ID) REFERENCES TEAM,
FOREIGN KEY (GAME_ID) REFERENCES GAME,
FOREIGN KEY (SEASON_ID) REFERENCES SEASON);

CREATE TABLE INJURY(
INJURY_ID DECIMAL(12) NOT NULL,
INJURY_TYPE VARCHAR(32) NOT NULL,
PRIMARY KEY (INJURY_ID));

CREATE TABLE PLAYER_INJURY_LINK(
PLAYER_INJURY_LINK_ID DECIMAL(12) NOT NULL,
PLAYER_ID DECIMAL(12) NOT NULL,
INJURY_ID DECIMAL(12) NOT NULL,
INJURY_DATE DATE NOT NULL,
RECOVER_TIME DECIMAL(4),
PRIMARY KEY (PLAYER_INJURY_LINK_ID),
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER,
FOREIGN KEY (INJURY_ID) REFERENCES INJURY);

CREATE TABLE TRADE(
TRADE_ID DECIMAL(12) NOT NULL,
TRADE_TYPE VARCHAR(32) NOT NULL,
TRADE_DATE DATE NOT NULL,
PRIMARY KEY (TRADE_ID));

CREATE TABLE PLAYER_TRADE_LINK(
PLAYER_TRADE_LINK_ID DECIMAL(12) NOT NULL,
PLAYER_ID DECIMAL(12) NOT NULL,
TRADE_ID DECIMAL(12) NOT NULL,
PLAYER_SALARY DECIMAL(12) NOT NULL,
PRIMARY KEY (PLAYER_TRADE_LINK_ID),
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER,
FOREIGN KEY (TRADE_ID) REFERENCES TRADE);

CREATE TABLE TEAM_TRADE_LINK(
TEAM_TRADE_LINK_ID DECIMAL(12) NOT NULL,
TEAM_ID DECIMAL(12) NOT NULL,
TRADE_ID DECIMAL(12) NOT NULL,
TEAM_TOTAL_SALARY DECIMAL(12) NOT NULL,
PRIMARY KEY (TEAM_TRADE_LINK_ID),
FOREIGN KEY (TEAM_ID) REFERENCES TEAM,
FOREIGN KEY (TRADE_ID) REFERENCES TRADE);

CREATE TABLE GUARD(
PLAYER_ID DECIMAL(12) NOT NULL,
PASSING_SKILL DECIMAL(3) NOT NULL,
PRIMARY KEY (PLAYER_ID),
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID));

CREATE TABLE FORWARD(
PLAYER_ID DECIMAL(12) NOT NULL,
SCORING_ABILITY DECIMAL(3) NOT NULL,
PRIMARY KEY (PLAYER_ID),
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID));

CREATE TABLE CENTER(
PLAYER_ID DECIMAL(12) NOT NULL,
DEFENSIVE_IMPACT DECIMAL(3) NOT NULL,
PRIMARY KEY (PLAYER_ID),
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID));

--SEQUENCES
CREATE SEQUENCE player_seq START WITH 1;
CREATE SEQUENCE team_seq START WITH 1;
CREATE SEQUENCE game_seq START WITH 1;
CREATE SEQUENCE player_game_link_seq START WITH 1;
CREATE SEQUENCE team_game_link_seq START WITH 1;
CREATE SEQUENCE season_seq START WITH 1;
CREATE SEQUENCE season_type_seq START WITH 1;
CREATE SEQUENCE player_birth_seq START WITH 1;
CREATE SEQUENCE injury_seq START WITH 1;
CREATE SEQUENCE player_injury_link_seq START WITH 1;
CREATE SEQUENCE trade_seq START WITH 1;
CREATE SEQUENCE player_trade_link_seq START WITH 1;
CREATE SEQUENCE team_trade_link_seq START WITH 1;

